### ISSUE TITLE
error code 500 

### ISSUE THREAD

**Issue by jakkuhh** [Senither/ShareX-Media-Server#34] opened 2022-01-22 16:00 UTC
error code 500 now what is the fix

**Comment by Senither** [comment] 2022-01-24 09:14
The error tells me absolutely nothing, the error could be caused by any number of things..

Can you include the `storage/logs/laravel.log` file output? Should include what is going wrong.

**Comment by jakkuhh** [comment] 2022-01-24 12:28
[message.txt](https://github.com/Senither/ShareX-Media-Server/files/7925492/message.txt)


log output

**Comment by teo0781** [comment] 2022-01-24 12:47
Sorry for interjecting, on what page does the error occur? This seems like a puppeteer issue (by the message), is this by any chance on the link shortener section?

**Comment by jakkuhh** [comment] 2022-01-24 12:59
> Sorry for interjecting, on what page does the error occur? This seems like a puppeteer issue (by the message), is this by any chance on the link shortener section? Are you also using Docker or not?

its either when using the link shortener on sharex or on the site its self and no im not using docker

**Comment by teo0781** [comment] 2022-01-24 13:03
Try this: `apt install libnss` and `apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev`
[SO answer](https://stackoverflow.com/questions/58134793/error-while-loading-shared-libraries-libnss3-so-while-running-gtlab-ci-job-to)

**Comment by jakkuhh** [comment] 2022-01-24 14:10
libnss fixed it and yes i know i just was fooling about on webstorm itll be going back on later after i add a few more things to it :)

**Comment by teo0781** [comment] 2022-01-24 14:51
If the issue was fixed, you should close this issue. Have a good day.

**Closed** 2022-01-24 16:23 UTC
